=== Tuyuyi99/presentacionXML/xsd/ejercicio1/futbol.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="futbol">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="equipo" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="nombre" type="xs:string"></xs:element>
                    <xs:element name="entrenador" type="xs:string"></xs:element>
                    <xs:element name="jugador" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nombreJugador" type="xs:string"></xs:element>
                                <xs:element name="nacionalidad" type="xs:string"></xs:element>
                            </xs:sequence>
                            <xs:attribute name="posicion" type="xs:string" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Tuyuyi99/presentacionXML/xsd/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<futbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="futbol.xsd">
    <equipo>
        <nombre>Real Madrid Club de Fútbol</nombre>
        <entrenador>Zinedine Zidane</entrenador>
        <jugador posicion='Delantero'>
            <nombreJugador>Eden Hazard</nombreJugador>
            <nacionalidad>Belga</nacionalidad>
        </jugador>
        <jugador posicion='Defensa'>
            <nombreJugador>Sergio Ramos</nombreJugador>
            <nacionalidad>Española</nacionalidad>
        </jugador>
    </equipo>
    <equipo>
        <nombre>París Saint-Germain Football Club </nombre>
        <entrenador>Mauricio Pochettino</entrenador>
        <jugador posicion='Delantero'>
            <nombreJugador>Neymar</nombreJugador>
            <nacionalidad>Brasileña</nacionalidad>
        </jugador>
        <jugador posicion='Centrocampista'>
            <nombreJugador>Ángel Di María</nombreJugador>
            <nacionalidad>Argentina</nacionalidad>
        </jugador>
    </equipo>
</futbol>
