=== Tuyuyi99/presentacionXML/dtd/ejercicio1/direccion.dtd
<!ELEMENT calles (direccion*)>
    <!ELEMENT direccion (via?, nombre_via*, numero?, portal?)>
            <!ATTLIST direccion id ID>
        <!ELEMENT via EMPTY>
            <!ATTLIST via tipo (calle | avenida) #REQUIRED>
        <!ELEMENT nombre_via (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT portal (#PCDATA)>

=== Tuyuyi99/presentacionXML/dtd/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE curriculo SYSTEM "direccion.dtd">
<calles>
    <direccion id="D1">
        <via tipo="calle"/>
        <nombre_via>Pablo Iglesias</nombre_via>
        <numero>104</numero>
    </direccion>

    <direccion id="D2">
        <via tipo="avenida"/>
        <nombre_via>Don jose</nombre_via>
        <portal>32</portal>
    </direccion>
</calles>
